name: Velocity - Bug Report
description: Report a problem, issue or a bug.
title: "Minecraft Version: Issue Title"
labels: [velocity]
body:


- type: markdown
  attributes:
    value: |
      ### Please edit the title like this: 1.x.x: Issue      
      Example: 1.20.5: Chat event loses its format
      _Do NOT put "Paper" or "Spigot" etc. in your title._


- type: input
  attributes:
    label: Error log (if applicable)
    description: If you are reporting a console error, upload any relevant log excerpts to either https://paste.gg or https://gist.github.com, save and the paste the link in this box.
    placeholder: "Paste link here"
  validations:
    required: false


- type: textarea
  attributes:
    label: '"/chc debug" output (strongly recommended)'
    description: |
      Run `/chc debug` in the console, then a debug ZIP file will be generated.
      
      **If you want to keep your settings private** Upload this ZIP file to [ufile.io](https://ufile.io) then email the link to support@mineacademy.org
      If you don't mind sending it publicly, simply upload the ZIP file in the space below.
    placeholder: |
      Click here then drag the ZIP file here to upload it.
  validations:
    required: false


- type: textarea
  attributes:
    label: Information about the issue/bug
    description: How can we reproduce your issue?
  validations:
    required: true
