
blank_issues_enabled: false
contact_links:
  - name: View common issues
    url: https://github.com/kangarko/ChatControl-Red/wiki/Common-Issues
    about: Check the list of known common issues to see if it solves your problem.
  - name: Ask volunteers on Discord
    url: https://mineacademy.org/discord
    about: Please note that kangarko answers tickets only at GitHub.
